### ISSUE TITLE
panic: open stub/vars.go: no such file or directory

### ISSUE THREAD

**Issue by Renaud-Pagin** [guitmz/ezuri#1]
Missing files ;-)

/Edit : ok my mistake i moved binary file to another folder, if i run the bin with the install folder, binary are well encrypted with no error ( can be closed ).

**Comment by guitmz** [comment]
@Renaud-Pagin cool! yeah I should make this more clear, I will update the readme soon, its my bad I still haven't done it yet, sorry!
